package net.corekit.monetize.ads

object AdPosition {
    const val SP_APP_START = "SP_AppStart"

    const val IV_BLOOD_SUGAR_BACK = "IV_BloodSugar_back"
    const val IV_BLOOD_PRESSURE_BACK = "IV_BloodPressure_back"
    const val IV_CHOLESTEROL_BACK = "IV_Cholesterol_back"
    const val IV_HEART_RATE_BACK = "IV_HeartRate_back"
    const val IV_BMI_BACK = "IV_BMI_back"
    const val IV_WATER_BACK = "IV_Water_back"
    const val IV_WALK_BACK = "IV_Walk_back"
    const val IV_STEP_SETTING_BACK = "IV_Step_Setting_back"

    const val IV_BLOOD_SUGAR_SAVE = "IV_BloodSugar_Save"
    const val IV_BLOOD_PRESSURE_SAVE = "IV_BloodPressure_Save"
    const val IV_CHOLESTEROL_SAVE = "IV_Cholesterol_Save"
    const val IV_HEART_RATE_SAVE = "IV_HeartRate_Save"
    const val IV_BMI_SAVE = "IV_BMI_Save"
    const val IV_STEP_GOAL_SAVE = "IV_Step_Goal_Save"

    const val IV_ADD_MEDS_BACK = "IV_AddMeds_back"
    const val IV_ADD_MEDS_SAVE = "IV_AddMeds_Save"
    const val IV_PROFILE_BACK = "IV_Profile_back"
    const val IV_INSIGHTS_DETAILS_BACK = "IV_InsightsDetails_back"

    const val IV_BLOOD_SUGAR_TRACK_BACK = "IV_BloodSugarTrack_back"
    const val IV_BLOOD_PRESSURE_TRACK_BACK = "IV_BloodPressureTrack_back"
    const val IV_CHOLESTEROL_TRACK_BACK = "IV_CholesterolTrack_back"
    const val IV_HEART_RATE_TRACK_BACK = "IV_HeartRateTrack_back"
    const val IV_BMI_TRACK_BACK = "IV_BMITrack_back"
    const val IV_WATER_TRACK_BACK = "IV_WaterTrack_back"
    const val IV_WALK_TRACK_BACK = "IV_WalkTrack_back"

    const val IV_BLOOD_SUGAR_TRACK_ENTER = "IV_BloodSugarTrack_Enter"
    const val IV_BLOOD_PRESSURE_TRACK_ENTER = "IV_BloodPressureTrack_Enter"
    const val IV_CHOLESTEROL_TRACK_ENTER = "IV_CholesterolTrack_Enter"
    const val IV_HEART_RATE_TRACK_ENTER = "IV_HeartRateTrack_Enter"
    const val IV_BMI_TRACK_ENTER = "IV_BMITrack_Enter"
    const val IV_WATER_TRACK_ENTER = "IV_WaterTrack_Enter"
    const val IV_WALK_TRACK_ENTER = "IV_WalkTrack_Enter"

    const val RV_BLOOD_SUGAR_NOTE = "RV_BloodSugar_Note"
    const val RV_BLOOD_PRESSURE_NOTE = "RV_BloodPressure_Note"
    const val RV_CHOLESTEROL_NOTE = "RV_Cholesterol_Note"
    const val RV_HEART_RATE_NOTE = "RV_HeartRate_Note"
    const val RV_BMI_NOTE = "RV_BMI_Note"

    const val NA_HOME_EXIT_DIALOG = "NA_Home_exit_dialog"
    const val NA_MAIN_TRACKER_MIDDLE = "NA_Main_Tracker_middle"
    const val NA_HYDRATE_COMPLETE_BOTTOM = "NA_Hydrate_Complete_bottom"
    const val NA_MEDS_REMINDER_LIST = "NA_Meds_reminder_list"
    const val NA_ALARM_MANAGER_BOTTOM = "NA_Alarm_Manager_bottom"
    const val NA_INSIGHTS_DETAIL_BOTTOM = "NA_Insights_detail_bottom"
    const val NA_SETTINGS_PROFILE_BOTTOM = "NA_Settings_profile_bottom"
    const val NA_SETTINGS_LANGUAGE_BOTTOM = "NA_Settings_language_bottom"
    const val NA_NEW_RECORD_BLOOD_SUGAR_BOTTOM = "NA_NewRecord_BloodSugar_bottom"
    const val NA_NEW_RECORD_BLOOD_PRESSURE_BOTTOM = "NA_NewRecord_BloodPressure_bottom"
    const val NA_NEW_RECORD_CHOLESTEROL_BOTTOM = "NA_NewRecord_Cholesterol_bottom"
    const val NA_NEW_RECORD_HEART_RATE_BOTTOM = "NA_NewRecord_HeartRate_bottom"
    const val NA_HEART_RATE_MEASURE_BOTTOM = "NA_HeartRateMeasure_bottom"
    const val NA_NEW_RECORD_BMI_BOTTOM = "NA_NewRecord_BMI_bottom"
    const val NA_DETAIL_BLOOD_SUGAR_BOTTOM = "NA_Detail_BloodSugar_bottom"
    const val NA_DETAIL_BLOOD_PRESSURE_BOTTOM = "NA_Detail_BloodPressure_bottom"
    const val NA_DETAIL_CHOLESTEROL_BOTTOM = "NA_Detail_Cholesterol_bottom"
    const val NA_DETAIL_HEART_RATE_BOTTOM = "NA_Detail_HeartRate_bottom"
    const val NA_DETAIL_BMI_BOTTOM = "NA_Detail_BMI_bottom"
    const val NA_DETAIL_CONFIRM_DIALOG = "NA_Detail_confirm_dialog"
    const val NA_UNINSTALL_1_BOTTOM = "NA_Uninstall1_bottom"
    const val NA_UNINSTALL_2_BOTTOM = "NA_Uninstall2_bottom"
    const val IV_UNINSTALL_1 = "IV_Uninstall1"
    const val IV_UNINSTALL_2 = "IV_Uninstall2"
    const val NA_EARTHQUAKE_BOTTOM = "NA_Earthquake_bottom"
    const val BA_HOME_BOTTOM = "BA_Home_bottom"
    const val NA_NEW_GUIDE_FULL = "NA_New_Guide_Full"
    const val NA_ALARM_CONFIG_DIALOG = "NA_Alarm_Config_Dialog"
}
